#!/usr/bin/perl

use strict ;

undef $/ ;

{
  my $s ;
  while ($s = <ARGV>) {

    $s =~ s,.*: added to search path.*\n,,g ;
    $s =~ s,.*: loaded.*\n,,g ;
    $s =~ s,#<\|(?:[^\|]|\|[^>])*\|>\n?,,gs ;

    print $s;
  }
}
