#!/bin/bash -x

rm -rf gen/*
for v in \
    12 \
    11 \
    10 \
    09 \
    08 \
    07 \
    06 \
    05 \
    04 \
    03 \
    02 \
	     ;
    do
    ./DOIT 4 $v
    done

./DOIT 4 13 ~alpha2
